resources:
- repo: self

trigger:
  branches:
    include:
    - '*'

jobs:
- job: LinuxAMD64
  pool:
    vmImage: 'ubuntu-16.04'
  workspace:
    clean: 'all'
  strategy:
    matrix:
      TPM_SIMULATOR_ON:
        TPM_SIMULATOR: 'ON'
        ARCH: 'AMD64'
      TPM_SIMULATOR_OFF:
        TPM_SIMULATOR: 'OFF'
        ARCH: 'AMD64'
  steps:
    - script: |
        docker run -v `pwd`:/workspace -v $OUTPUT_DIR:/output -i --rm --privileged debian:9 build.sh
      env:
        SDK_TAG: '2019-05-16'
        OUTPUT_DIR: $(Build.ArtifactStagingDirectory)
      displayName: 'Build'
    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: 'LinuxAMD64'
        targetPath: $(Build.ArtifactStagingDirectory)
